### PR TITLE
Fix some plugin links that are no longer valid

### PR DESCRIPTION
**Pull request by leihaojun**

### CODE REVIEW

**Comment by AnirudhG07** [comment]
Please see #8, we cannot add the give plugins without permissions. I have already created the branch for it. I am updated with DreamMaoMao's plugins.

**Comment by leihaojun** [comment]
I see that these warehouses are all using mit LICENSE, which should be the meaning of authorizing other uses?

**Comment by AnirudhG07** [comment]
I didnt get your question properly,
but as far as i understood, yes all plugins use MIT license and as github suggests, anyone can use them for their own use, as they like. If you have a ques on MIT license, do checkout the github docs for MIT license.
If your ques means that if it MIT license, why cant we add gitee plugins of DreamMaoMao here, well answer to that is independent of MIT license, its just one shoudnt add anything here without the permission of the author, as sxyazi told me in PR mentioned before.
Pls make your question clear, if i didnt answer you properly

**Comment by leihaojun** [comment]
I don't think we need to ask the author's permission to recommend  their tools in your readme, because we are just recommending them.
And like the other tools that is already in your readme,.  you may also  haven't  asked the permission of their author.   But I also understand that this feeling may involve other things outside the rules (such as whether you like ).

**Comment by AnirudhG07** [comment]
i agree with your point. That's why i made the pr for it, but after that convo, i didnt want to go against it particularly either.

**Comment by sxyazi** [comment]
> If needed, I second @leihaojun
> 
> If something exists, is open-source, and is publicly available, it could be added without consent. Whatever the project license.
> 
> The only logic I would agree with, and anyone would I think, is that if someone complain about being listed it can be removed

Fair enough! Maybe in the future we can just add them directly without having to go to their repo to ask. If someone objects to adding them, we can remove them then

**Comment by AnirudhG07** [comment]
Yes I have been asking each one, to add a license to download so that we can download them by `ya pack`, and they well agreed and made PR's here. So if it ever become an issue, we can fix it.

**Comment by AnirudhG07** [comment]
I hope #20  helps you guys out. Feel free to add any other resource based plugins or flavours you guys find. If they have license, we ll add it here, after a review for Security reasons, as mentioned in one of the discussions in yazi repo.

**Pull request closed without merging**
