### PR TITLE
docs: add some new plugins from `yazi-rs` org

### PR DESCRIPTION
**Pull request by sxyazi**
Thanks for creating your package and adding in awesome-yazi.
Please add your package in the following format to allow users to access your plugin as well as to increase ease to download them.

<details>
<summary>
<a href="https://github.com/author_name/package.yazi">package.yazi</a> - A brief description about your package.
</summary>

```bash
# This contains downloading instruction, prefer `ya pack`, if not, git clone instruction will do.
ya pack -a author_name/package
```

</details>

<br>

- [x] I have read the [CONTRIBUTING.md](CONTRIBUTING.md) file.
- [x] I have added my package in ascending order in the sub-section of chosen category.
- [x] I have added in the format mentioned above.

This PR also removed https://github.com/redbeardymcgee/yazi-plugins/tree/main/git-status.yazi because it was a duplicate of DreamMaoMao/git.yazi and has been archived

@AnirudhG07  Should we clean up other plugins from https://github.com/redbeardymcgee/yazi-plugins that are already archived?

### CODE REVIEW

**Comment by AnirudhG07** [comment]
Yes if you notice, if I have give it optional, but replace with the original one from gitee.
Maybe ill clean it up, and simply add its mention in cool-findings(maybe rename it).

**Comment by AnirudhG07** [comment]
You didnt add git.yazi?

**Comment by sxyazi** [comment]
> You didnt add git.yazi?

Already there 
screenshot-002005


Just after Mao's, and I also added a username as a prefix to better distinguish

**Comment by AnirudhG07** [comment]
Oops! didnt notice. My bad

**Review by AnirudhG07 — APPROVED** [review]
Thanks for adding the plugins and the cleanup. Ill also do some more changes later on!

**Comment by AnirudhG07** [comment]
Hey I noticed. You didnt add `mime-ext` plugin. it's present in `yazi-rs`. Any particular reason?

**Comment by sxyazi** [comment]
Ah indeed, could you add it? - all plugins under `yazi-rs` can be added freely

**Comment by AnirudhG07** [comment]
Sure I'll put it for now. But I would like you putting yazi-rs plugins. Also check disc DM, I mentioned something related to docs. Lemme know thoughts.

**Pull request merged**
